language: node_js
node_js:
  - "stable"
sudo: false
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: rolan-tic-tac-toe
  local_dir: build
  on:
    branch: master